name: Lint

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Black
      run: pip3 install black
    - name: Check with Black
      run: python3 -m black --check .
